### ISSUE TITLE
Empty context menu still displays padding, instead nothing should be displayed

### ISSUE THREAD

**Issue by lschirmbrand** [node-projects/web-component-sidebar#1]
![image](https://github.com/node-projects/web-component-sidebar/assets/61965786/637387fb-d0a9-408f-8fa2-205f456f4398)

Should be easy to fix. Css selector for the ul in the context menu already exists. New selector could be added like so:

```css
  contextmenu>ul:has(*) {
      padding: xyz;
  }
```
